In [ ]:
import numpy as np

### Numpy Notes
NumPy arrays are called **ndarray** objects, nd stands for n - dimension
1-D numpy array is vector, 2-D is matrix.



In [ ]:
array=np.array([1, 2, 3, 4, 5]) # creates a 1-D array
print(type(array))

**how to create an array in numpy ?**

numpy.array(list) this is the general form 
 
or numpy.array([1,2....])

In [ ]:
#eg:
np.array([1, 2, 3, 4, 5]) # creates a 1-D array

#or
k=[1,2,3,4,5]
np.array(k)


In [ ]:
the_first_arr_we_created = np.array(k) #or np.array([1, 2, 3, 4, 5])  creates a 1-D array
print(the_first_arr_we_created) # here we need to use print function to see the output in the console
                                # after establishing variable it won't show the output in the console by just running 
                                # but we can type that established variable name in the console to see the output even if we didn't use print(variable)
# to check dimesions of the array we use .ndim
print(the_first_arr_we_created.ndim) # 1-D array

**what is the difference between a list and an array ?.**
- list can store different data type

- eg:[1,2,"apple"]

- but array can only store same data type 

- eg1: all integer or all floats, it can store strings also but there are some things to
 learn there **for future**
 
- eg2: the code given below


In [ ]:
# as we know k is a list
print(k*2) # this will print the list twice
print(the_first_arr_we_created*2) # this will not print the array twice, but it multiplies each element by 2

**Two-D array** 

2-D array is  a matrix   
 
It can be created using the numpy.array() function by passing a list of lists as the 

argument, where each inner list represents a row in the matrix. For example, the following 

code creates a 4x3 matrix:

In [ ]:
h=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # look each inner list is a row in the matrix and determines the number of rows in the matrix 
                                    # the number of elements in each inner list determines the number of columns in the matrix
print(h)
print(h.size) # prints the number of elements in the array
print(h.ndim) # prints the number of dimensions of the array
print(h.shape) # prints the shape of the array (number of rows, number of columns)
print(h.dtype) # prints the data type of the elements in the array
print(h[0]) # prints the first row of the array
print(h[0][0]) # prints the first element of the first row of the array

**3-D array**  

A three-dimensional array in NumPy is an array of arrays, where each inner array represents 

a two-dimensional matrix.

its like it have three matrix(2-d array) 

![Numpy Example](https://media.geeksforgeeks.org/wp-content/uploads/20240911184000/3d-array-breakdown.webp)



![Numpy Example](https://media.geeksforgeeks.org/wp-content/uploads/20240911183848/3d-array-in-c.webp)


In [ ]:
#example for 3-D array
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]) # creates a 3-D array
print(arr3)
print(arr3.shape) #(2, 3, 3) # 2 matrices, each with 3 rows and 3 columns


**Reshape An Array**  

We can use reshape() to reshape an existing array, which change the shape of an existing array.

Using it we can change no of elements in each dimension & also change the dimension. 

also note that $A^T$ is a reshaping.


![Description](image.png)

1.**1-D to 2-D array** 
 
eg: we are converting a 1-D array(6) to 2-D array (2,3)


In [ ]:
arr1=np.array([1,2,3,4,5,6]) #it creates a 1-D array
print(arr1,"is the 1-D array")
arr2=arr1.reshape(2,3)
print(arr2,"is the 2-D array")

**2. 1-D to 3-D array** 

![Description](hihi.png)  

here we are converting (8) to (2,2,2) 
 
ie from [1,2,3,4,5,6,7,8] to [[[1,2],[3,4]],      
```                       ``` [[5,6],[7,8]]]     

In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8])
arr3=arr1.reshape(2,2,2) #it creates a 3-D array
print(arr3,"is the 3-D array")

**3. 2-D to 3-D array**


In [ ]:
arr2=np.array([[1,2,3,4],[3,4,5,6]])
arr3=np.array([[[1,2],[3,4]],[[3,4],[7,8]]]) #it creates a 3-D array
print(arr3,"is the 3-D array")
arr4=arr2.reshape(2,2,2) #it creates a 3-D array
print (arr4,"is the 3-D array")

**to convert any dimension to 1-D**  

**note:**use this code : arr1d=arr.reshape(-1)

In [ ]:
arr5=arr4.reshape(-1) #to convert any dimension to 1-D
print(arr5,"is the 1-D array")

### Data types in Numpy ###
![Numpy Example](https://1.bp.blogspot.com/-xrnk-4zD2Ac/W1LCbjrSjjI/AAAAAAAAXUY/8QJ0AZBxsQ0h6BgUV4kml0NqIO_hOs2KwCLcBGAs/s1600/4212_t2-1.PNG)  

**Why Do We Need to Specify Data Types (dtypes) in NumPy?**  
- Unlike Python lists (which store flexible objects), NumPy arrays store data in contiguous memory blocks.  
Each element has a fixed size (e.g., int32 = 4 bytes, float64 = 8 bytes).  

Example: For large arrays, using int16 instead of int64 reduces memory usage by 75%.  

- Some libraries (e.g., TensorFlow, PyTorch) require specific dtypes.
GPUs work best with float32 (not Python’s default float64).

- there are many examples:  


Problem: Integers have fixed ranges (e.g., int8 = -128 to 127). Large numbers cause overflow:


In [77]:
arr = np.array([100, 200, 300], dtype='int8')  # Fails! 300 > 127 you can see cast overflows in error message if you run this

/var/folders/1t/v6x5wtq16578dh60q4cgw8x80000gn/T/ipykernel_19787/3310169046.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([100, 200, 300], dtype='int8')  # Fails! 300 > 127 you can see cast overflows in error message if you run this
/var/folders/1t/v6x5wtq16578dh60q4cgw8x80000gn/T/ipykernel_19787/3310169046.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([100, 200, 300], dtype='int8')  # Fails! 300 > 127 you can see cast overflows in error message if you run this


Solution: Convert to a larger dtype (int16, int32, or float):

In [78]:
arr_safe = arr.astype('int16')  # Now works

**We can create array with specific data types**



**we  also can convert the data type of array to other datatype by using astype() function**

In [79]:
k=np.array([1,2,3,4,5])
print(k.dtype)  # prints the data type of the elements in the array
# out put print the default data type of the array


# if you want to change the data type of the array you can use the astype()
k_float = k.astype('float32')  # converts the array to float32 data type
print(k_float.dtype)  # prints the data type of the elements in the array after conversion


# you can also use the dtype parameter in the np.array() function to create an array with a specific data type
k_int = np.array([1, 2, 3, 4, 5], dtype='int32')  # creates an array with int32 data type
print(k_int.dtype)  # prints the data type of the elements in the array after creation


# you can also use the np.float32() function to create an array with float32 data type
k_float32 = np.float32([1, 2, 3, 4, 5])  # creates an array with float32 data type
print(k_float32.dtype)  # prints the data type of the elements in the array after creation

int64
float32
int32
float32


**Array Indexing**

**for 1-D array** 

same as list logic for 1-D array ([1,2,3,4] → 0,1,2,3 index )

**for 2-D array**  

same like  maths matrix but start from zero instead of 1

a<sub>11</sub> in maths is a<sub>00</sub> in array

we call it as array[1,0] gives first element.

**for 3-D array**

we call it like array[matrix number, 2-D index, 2-D index]

so the shorcut for 2-D index is a<sub>k-1,n-1</sub>    n,k are maths matrix notation

for example:





In [80]:
f=np.array([[[1,2,3,],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(f)  # creates a 3-D array
print(f[0,0,0])  # prints the first element of the first row of the first matrix of the 3-D array
print(f[0,0,1])  # prints second element of first matrix
print(f[1,1,1]) #prints a22(maths notation) of second matrix 

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
1
2
14


**Array slicing**  

Slicing is a way to select parts of an array by specifying start, stop, and step values.

array[start:stop:step]

start: Index where the slice begins (inclusive). Default = 0

stop: Index where the slice ends (exclusive). Default = len(array)

step: How many elements to skip. Default = 1

note: start includes the element in we mentioned in slicing index but end excludes the 

element index we wrote in slicing index.

you may feel like if end index is n we get last element from index of (n-step) this works 

for most cases but its not true its only true  if (end - step) lies on the step path

starting from start. sometimes end - step goes beyond starting index for example.


In [81]:
arr = list(range(10))  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

k=arr[0:6:2]  # → [0, 2, 4]
print(k)

arr[3:7:5]  # → [3] but 7 - 5 is 2 ie element 2 which is not write

[0, 2, 4]


[3]

arr = np.array([10, 20, 30, 40, 50])

these are simple examples:

print(arr[1:4])  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  gives &nbsp;&nbsp;&nbsp;  [20, 30, 40] (indexes 1 to 3)

print(arr[:3])   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; gives &nbsp;&nbsp;&nbsp;  [10, 20, 30] (start to index 2)  

print(arr[2:])   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  gives  &nbsp;&nbsp;&nbsp; [30, 40, 50] (index 2 to end)  

print(arr[::2])   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   gives &nbsp;&nbsp;&nbsp;  [10, 30, 50] (every 2nd element)  


Negative Indices: Count from the end  

arr = np.array([10, 20, 30, 40]) &nbsp;&nbsp;&nbsp;(negative index is -4,-3,-2,-1)   

print(arr[-3:-1]) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   gives  [20, 30] &nbsp;&nbsp;&nbsp;(3rd from end to 1st from end) (direction is still left to right)( exclued last element -1)  

arr[:] &nbsp;&nbsp;&nbsp;	 copy full array  ,	Default start=0, end=len(arr)  

arr[3:]	 &nbsp;&nbsp;&nbsp;From index 3 to end	Omitting end , includes everything after start  

arr[::-1] &nbsp;&nbsp;&nbsp;	Reversed array &nbsp;&nbsp;&nbsp;	, Negative step reverses direction  

note:end is always excluded (like how range(0, 5) generates 0-4).  

first_half = arr[:len(arr)//2]  &nbsp;&nbsp;&nbsp; gives  0 to mid , len of array is last index + 1  

second_half = arr[len(arr)//2:]  &nbsp;&nbsp;&nbsp; gives mid to end  


**How to get rows and coloumns from array**  

1. **2-D array**




In [83]:
b = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

**to get row and coloumn :**  

in 2-D:

for row:

we can either use a[i] or a[i,:] 

note : consider imaginery start and end in :  , so a[i,:] means  $i^th$ row and iterate 

through start to end

for column:  

a[:, j]


In [89]:
print(b[0] )      # → [1, 2, 3]  → 1st row 
print(b[1, :])    # → [4, 5, 6]  → 2nd row
print(b[0:2,:])   # prints the first two rows
print(b[-1,:])  # → [7, 8, 9]  → last row
print(b[:, 1])  # → [2, 5, 8]  → 2nd column
print(b[:, 1:3])  # → [[2, 3], [5, 6], [8, 9]]  → 2nd and 3rd columns

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[7 8 9]
[2 5 8]
[[2 3]
 [5 6]
 [8 9]]


for 3-D  rows and columns :

a[d, i, :] , so $d^th$ matrix, $i^th$ row , iterate from start to end within i 



In [92]:
c = np.array([
  [ [1, 2, 3],
    [4, 5, 6] ],

  [ [7, 8, 9],
    [10, 11, 12] ]
])
# Shape: (2 matrix, 2 rows, 3 columns)

print(c[0])       # prints the first matrix
print(c[0, 0, :])  # → [1, 2, 3]  → 1st matrix, 1st row
print(c[1, 1, :])  # → [10, 11, 12]  → 2nd matrix, 2nd row
print(c[0, 0, 1])  # → 2  → 1st matrix, 1st row, 2nd element
print(c[0,0:2,:])  #prints the first two rows of the first matrix (the last two indexes are same like 2-D)


[[1 2 3]
 [4 5 6]]
[1 2 3]
[10 11 12]
2
[[1 2 3]
 [4 5 6]]


**Assigning values to an array**

In [94]:
# assigning values to an array.
d = np.array([1, 2, 3, 4, 5])
d[0] = 10  # changes the first element to 10
print(d)  # prints the modified array
g=np.array([[1,2,3],[4,5,6],[7,8,9]])
g[0,0]=10 # changes the first element of the first row to 10
print(g)  # prints the modified array
g[-3:-1,:] = [[11, 12, 13], [14, 15, 16]]  # changes the first two rows to new values
print(g)  # prints the modified array   

[10  2  3  4  5]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[11 12 13]
 [14 15 16]
 [ 7  8  9]]


** Arrays of Zeros in NumPy**

general form is zero_array=np.zeros((shape)), shape can be (k) for k element in 1-D, (x,y) for 2-D etc.

note:zero_array=np.zeros(1,2) gives error but zero_array=np.zeros((1,2)) is correct

Arrays filled with zeros are fundamental in scientific computing and data science.

Machine Learning: Weights in neural networks are often initialized to zeros before training.

Machine Learning: Weights in neural networks are often initialized to zeros before training.


In [ ]:
k=np.zeros((3,3))  # creates a 3x3 array of zeros
print(k)  # prints the array of zeros

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [82]:
weights = np.zeros((100, 50))  # Layer with 100 inputs and 50 neurons
# a matrix of 100 rows and 50 columns filled with zeros

 **Masking and Filtering Data**  

Boolean Masks: Create filters to select data (zeros = False, ones = True).

bool is True for any Non-zero number like 1, 2,-5 etc.

and False only for zero.

bool(1)   # True  

bool(0)   # False  

bool(5)   # True  

bool(-3)  # True  



In [95]:
data=np.array([1, 2, 3, 4, 5])
mask=np.zeros(5, dtype=bool)  # creates a boolean mask of the same shape as data, initialized to False
mask[-2:] = True  # sets the last two elements of the mask to True
print(mask)  # prints the mask
print(data[mask])  # prints the elements of data where mask is True, i.e [4, 5]

[False False False  True  True]
[4 5]


 **Padding Arrays for Operations**  

Signal Processing: Zero-padding ensures proper alignment in Fourier transforms.  

In [ ]:
signal = np.array([1, 2, 3])
padded = np.zeros(5)  # [0, 0, 0, 0, 0]
padded[1:4] = signal  # [0, 1, 2, 3, 0]

**Benchmarking and Testing**  

Performance Tests: Measure how long it takes to process large zero arrays.



In [98]:
big_array = np.zeros(10_000_000)  # 10 million elements
%timeit big_array.sum()  # Test summation speed

1.77 ms ± 5.96 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


**np.ones**  

creates a NumPy array filled entirely with the value 1. It's one of the most frequently used 

array initialization functions.  

same use like zeros for example in this also we can use boolean mask but here it is true for 

all element as 1 is a non-zero number 

In [102]:


# Create a 1D array of five 1's
arr_1d = np.ones(5)  
print(arr_1d)           # Output: [1., 1., 1., 1., 1.]

# Create a 2x3 matrix of 1's
arr_2d = np.ones((2, 3))
print(arr_2d)      # Output: [[1., 1., 1.], [1., 1., 1.]]

# With a specific data type (e.g., integers)
arr_int= np.ones(3, dtype=int)
print(arr_int)  # Output: [1, 1, 1]

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 1 1]
